# Generated by Django 5.0.4 on 2024-04-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acadamic', '0002_alter_degree_degree_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='subject id'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(max_length=200, verbose_name='subject name'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='degree_name',
            field=models.CharField(max_length=200, verbose_name='course name'),
        ),
    ]
