# Generated by Django 5.0.4 on 2024-04-28 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acadamic', '0003_alter_courses_course_id_alter_courses_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='degree_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acadamic.degree'),
        ),
    ]
