# Generated by Django 5.0.4 on 2024-04-28 19:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_profile', '0005_alter_profile_last_login'),
        ('acadamic', '0004_alter_courses_degree_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 1, 26, 32, 316003), verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='acadamic.degree'),
        ),
    ]
