# Generated by Django 5.0.4 on 2024-04-28 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_profile', '0009_alter_profile_last_login_alter_student_degree_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 2, 32, 14, 415964), verbose_name='last login'),
        ),
    ]
