# Generated by Django 5.0.4 on 2024-04-28 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_profile', '0010_alter_profile_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_phone',
            old_name='admin',
            new_name='admin_id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 2, 39, 15, 32629), verbose_name='last login'),
        ),
    ]
